import "./globals.css";
import { Jost } from "next/font/google";
import Header from "@/components/Header";

const alata = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Felsunny Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${alata.className} `}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
